/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: sanity/schema.json
export type Callout = {
  _type: "callout";
  tone?: "note" | "important";
  content: RichText;
};

export type PullQuote = {
  _type: "pullQuote";
  quote: string;
  attribution?: string;
};

export type VideoEmbed = {
  _type: "videoEmbed";
  provider: "youtube" | "vimeo";
  url: string;
  title: string;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type ArticleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "article";
};

export type TopicReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "topic";
};

export type PodcastEpisodeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "podcastEpisode";
};

export type VideoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "video";
};

export type BookReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "book";
};

export type RichText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        | {
            href: string;
            openInNewTab?: boolean;
            _type: "externalLink";
            _key: string;
          }
        | {
            reference:
              | PageReference
              | ArticleReference
              | TopicReference
              | PodcastEpisodeReference
              | VideoReference
              | BookReference;
            _type: "internalLink";
            _key: string;
          }
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & EditorialImage)
  | ({
      _key: string;
    } & VideoEmbed)
  | ({
      _key: string;
    } & PullQuote)
  | ({
      _key: string;
    } & Callout)
>;

export type MigrationMetadata = {
  _type: "migrationMetadata";
  wordpressId?: number;
  legacyUrl?: string;
  legacyCanonicalUrl?: string;
  legacyAuthor?: string;
  legacyCategories?: Array<string>;
  legacyTags?: Array<string>;
  legacyFeaturedImageUrl?: string;
  migrationAction?:
    "KEEP" | "UPDATE" | "CONSOLIDATE" | "REDIRECT" | "REMOVE" | "NOINDEX";
  manualReviewRequired?: boolean;
  notes?: string;
};

export type CtaLink = {
  _type: "ctaLink";
  label: string;
  href: string;
};

export type ExternalLink = {
  _type: "externalLink";
  label: string;
  url: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type EditorialImage = {
  _type: "editorialImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  decorative?: boolean;
  alt?: string;
  caption?: string;
  credit?: string;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  canonicalUrl?: string;
  noIndex?: boolean;
  noFollow?: boolean;
  socialTitle?: string;
  socialDescription?: string;
  socialImage: EditorialImage;
};

export type Redirect = {
  _id: string;
  _type: "redirect";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  source: string;
  destination: string;
  statusCode: 301 | 302 | 307 | 308;
  active?: boolean;
  migrationReason:
    "URL changed" | "Consolidated" | "Legacy alias" | "Temporary";
  notes?: string;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question: string;
  answer: RichText;
  contexts: Array<string>;
  relatedPages?: Array<
    {
      _key: string;
    } & PageReference
  >;
  order?: number;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote: string;
  story?: RichText;
  attributionName: string;
  attributionTitle?: string;
  attributionOrganization?: string;
  portrait: EditorialImage;
  videoUrl?: string;
  program?: PageReference;
  approvalStatus: "pending" | "approved" | "revoked";
  approvedAt?: string;
  featured?: boolean;
  order?: number;
  sourceNotes?: string;
  migration?: MigrationMetadata;
};

export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle: string;
  siteDescription: string;
  siteUrl: string;
  logo: EditorialImage;
  defaultSeo: Seo;
  defaultSocialImage: EditorialImage;
  primaryNavigation?: Array<
    {
      _key: string;
    } & CtaLink
  >;
  footerNavigation?: Array<
    {
      _key: string;
    } & CtaLink
  >;
  footerContent?: RichText;
  primaryCta?: CtaLink;
  contactEmail?: string;
  contactPhone?: string;
  socialProfiles?: Array<
    {
      _key: string;
    } & ExternalLink
  >;
  organizationName?: string;
  organizationDescription?: string;
  organizationLogo: EditorialImage;
  founder?: PersonReference;
  footerCopyright?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  pageKind: "standard" | "offer" | "roadmap" | "contact" | "legal";
  summary?: string;
  body?: RichText;
  heroImage: EditorialImage;
  primaryCta?: CtaLink;
  relatedContent?: ArrayOf<
    | ArticleReference
    | PodcastEpisodeReference
    | VideoReference
    | BookReference
    | TopicReference
  >;
  seo?: Seo;
  migration?: MigrationMetadata;
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  excerpt: string;
  body: RichText;
  author: PersonReference;
  publishedAt: string;
  updatedAt?: string;
  featuredImage: EditorialImage;
  primaryTopic: TopicReference;
  secondaryTopics?: Array<
    {
      _key: string;
    } & TopicReference
  >;
  relatedContent?: ArrayOf<
    | ArticleReference
    | PodcastEpisodeReference
    | VideoReference
    | BookReference
    | PageReference
  >;
  featured?: boolean;
  seo?: Seo;
  migration?: MigrationMetadata;
};

export type Topic = {
  _id: string;
  _type: "topic";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  shortDescription: string;
  introduction?: RichText;
  heroImage: EditorialImage;
  featuredContent?: ArrayOf<
    ArticleReference | PodcastEpisodeReference | VideoReference | BookReference
  >;
  relatedTopics?: Array<
    {
      _key: string;
    } & TopicReference
  >;
  seo?: Seo;
};

export type PodcastEpisode = {
  _id: string;
  _type: "podcastEpisode";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summary: string;
  publishedAt: string;
  author?: PersonReference;
  primaryTopic: TopicReference;
  secondaryTopics?: Array<
    {
      _key: string;
    } & TopicReference
  >;
  featuredImage: EditorialImage;
  featured?: boolean;
  seo?: Seo;
  migration?: MigrationMetadata;
  episodeNumber?: number;
  duration?: string;
  guests?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  guestNotes?: string;
  audioUrl?: string;
  platformLinks?: Array<
    {
      _key: string;
    } & ExternalLink
  >;
  videoUrl?: string;
  keyIdeas?: Array<string>;
  transcript?: RichText;
  showNotes?: RichText;
  relatedContent?: ArrayOf<
    | ArticleReference
    | PodcastEpisodeReference
    | VideoReference
    | BookReference
    | PageReference
  >;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  professionalTitle?: string;
  credentials?: Array<string>;
  shortBio: string;
  bio?: RichText;
  portrait: EditorialImage;
  alternativeImages?: Array<
    {
      _key: string;
    } & EditorialImage
  >;
  socialProfiles?: Array<
    {
      _key: string;
    } & ExternalLink
  >;
  sameAs?: Array<string>;
  website?: string;
  identityDescription?: string;
  knowsAbout?: Array<string>;
  seo?: Seo;
};

export type Video = {
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summary: string;
  publishedAt: string;
  author?: PersonReference;
  primaryTopic: TopicReference;
  secondaryTopics?: Array<
    {
      _key: string;
    } & TopicReference
  >;
  featuredImage: EditorialImage;
  featured?: boolean;
  seo?: Seo;
  migration?: MigrationMetadata;
  provider: "youtube" | "vimeo" | "other";
  videoUrl: string;
  providerVideoId?: string;
  duration?: string;
  keyTakeaways?: Array<string>;
  transcript?: RichText;
  notes?: RichText;
  relatedContent?: ArrayOf<
    | ArticleReference
    | PodcastEpisodeReference
    | VideoReference
    | BookReference
    | PageReference
  >;
};

export type Book = {
  _id: string;
  _type: "book";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  subtitle?: string;
  slug: Slug;
  description?: RichText;
  cover: EditorialImage;
  authors: Array<
    {
      _key: string;
    } & PersonReference
  >;
  publicationDate?: string;
  isbn?: string;
  purchaseLinks?: Array<
    {
      _key: string;
    } & ExternalLink
  >;
  primaryTopic?: TopicReference;
  relatedTopics?: Array<
    {
      _key: string;
    } & TopicReference
  >;
  relatedContent?: ArrayOf<
    ArticleReference | PodcastEpisodeReference | VideoReference | PageReference
  >;
  featured?: boolean;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Callout
  | PullQuote
  | VideoEmbed
  | PageReference
  | ArticleReference
  | TopicReference
  | PodcastEpisodeReference
  | VideoReference
  | BookReference
  | RichText
  | MigrationMetadata
  | CtaLink
  | ExternalLink
  | SanityImageAssetReference
  | EditorialImage
  | Seo
  | Redirect
  | Faq
  | Testimonial
  | PersonReference
  | SiteSettings
  | Page
  | Article
  | Topic
  | PodcastEpisode
  | Person
  | Video
  | Book
  | Slug
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/queries/content.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{  ..., founder->{name, "slug": slug.current, professionalTitle, portrait, sameAs}}
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: "siteSettings";
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle: string;
  siteDescription: string;
  siteUrl: string;
  logo: EditorialImage;
  defaultSeo: Seo;
  defaultSocialImage: EditorialImage;
  primaryNavigation?: Array<
    {
      _key: string;
    } & CtaLink
  >;
  footerNavigation?: Array<
    {
      _key: string;
    } & CtaLink
  >;
  footerContent?: RichText;
  primaryCta?: CtaLink;
  contactEmail?: string;
  contactPhone?: string;
  socialProfiles?: Array<
    {
      _key: string;
    } & ExternalLink
  >;
  organizationName?: string;
  organizationDescription?: string;
  organizationLogo: EditorialImage;
  founder: {
    name: string;
    slug: string;
    professionalTitle: string | null;
    portrait: EditorialImage;
    sameAs: Array<string> | null;
  } | null;
  footerCopyright?: string;
} | null;

// Source: sanity/queries/content.ts
// Variable: PERSON_BY_SLUG_QUERY
// Query: *[_type == "person" && slug.current == $slug][0]{  ..., "slug": slug.current}
export type PERSON_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: string;
  professionalTitle?: string;
  credentials?: Array<string>;
  shortBio: string;
  bio?: RichText;
  portrait: EditorialImage;
  alternativeImages?: Array<
    {
      _key: string;
    } & EditorialImage
  >;
  socialProfiles?: Array<
    {
      _key: string;
    } & ExternalLink
  >;
  sameAs?: Array<string>;
  website?: string;
  identityDescription?: string;
  knowsAbout?: Array<string>;
  seo?: Seo;
} | null;

// Source: sanity/queries/content.ts
// Variable: JACK_PROFILE_QUERY
// Query: *[_type == "person" && slug.current == "jack-skeen"][0]{  ..., "slug": slug.current}
export type JACK_PROFILE_QUERY_RESULT = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: string;
  professionalTitle?: string;
  credentials?: Array<string>;
  shortBio: string;
  bio?: RichText;
  portrait: EditorialImage;
  alternativeImages?: Array<
    {
      _key: string;
    } & EditorialImage
  >;
  socialProfiles?: Array<
    {
      _key: string;
    } & ExternalLink
  >;
  sameAs?: Array<string>;
  website?: string;
  identityDescription?: string;
  knowsAbout?: Array<string>;
  seo?: Seo;
} | null;

// Source: sanity/queries/content.ts
// Variable: ARTICLE_BY_SLUG_QUERY
// Query: *[_type == "article" && slug.current == $slug][0]{  ..., "slug": slug.current, author->{name, "slug": slug.current, professionalTitle, portrait},  primaryTopic->{title, "slug": slug.current}, secondaryTopics[]->{title, "slug": slug.current},  relatedContent[]->{_type, _id, title, "slug": slug.current, summary, excerpt, featuredImage}}
export type ARTICLE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: string;
  excerpt: string;
  body: RichText;
  author: {
    name: string;
    slug: string;
    professionalTitle: string | null;
    portrait: EditorialImage;
  };
  publishedAt: string;
  updatedAt?: string;
  featuredImage: EditorialImage;
  primaryTopic: {
    title: string;
    slug: string;
  };
  secondaryTopics: Array<{
    title: string;
    slug: string;
  }> | null;
  relatedContent: Array<
    | {
        _type: "article";
        _id: string;
        title: string;
        slug: string;
        summary: null;
        excerpt: string;
        featuredImage: EditorialImage;
      }
    | {
        _type: "book";
        _id: string;
        title: string;
        slug: string;
        summary: null;
        excerpt: null;
        featuredImage: null;
      }
    | {
        _type: "page";
        _id: string;
        title: string;
        slug: string;
        summary: string | null;
        excerpt: null;
        featuredImage: null;
      }
    | {
        _type: "podcastEpisode";
        _id: string;
        title: string;
        slug: string;
        summary: string;
        excerpt: null;
        featuredImage: EditorialImage;
      }
    | {
        _type: "video";
        _id: string;
        title: string;
        slug: string;
        summary: string;
        excerpt: null;
        featuredImage: EditorialImage;
      }
  > | null;
  featured?: boolean;
  seo?: Seo;
  migration?: MigrationMetadata;
} | null;

// Source: sanity/queries/content.ts
// Variable: ARTICLES_QUERY
// Query: *[_type == "article"] | order(publishedAt desc)[$offset...$limit]{  _id, title, "slug": slug.current, excerpt, publishedAt, updatedAt, featuredImage,  author->{name, "slug": slug.current}, primaryTopic->{title, "slug": slug.current}}
export type ARTICLES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  updatedAt: string | null;
  featuredImage: EditorialImage;
  author: {
    name: string;
    slug: string;
  };
  primaryTopic: {
    title: string;
    slug: string;
  };
}>;

// Source: sanity/queries/content.ts
// Variable: ARTICLES_BY_TOPIC_QUERY
// Query: *[_type == "article" && (primaryTopic->slug.current == $slug || $slug in secondaryTopics[]->slug.current)] | order(publishedAt desc){  _id, title, "slug": slug.current, excerpt, publishedAt, featuredImage,  author->{name, "slug": slug.current}, primaryTopic->{title, "slug": slug.current}}
export type ARTICLES_BY_TOPIC_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  featuredImage: EditorialImage;
  author: {
    name: string;
    slug: string;
  };
  primaryTopic: {
    title: string;
    slug: string;
  };
}>;

// Source: sanity/queries/content.ts
// Variable: FEATURED_ARTICLES_QUERY
// Query: *[_type == "article" && featured == true] | order(publishedAt desc)[0...$limit]{  _id, title, "slug": slug.current, excerpt, publishedAt, featuredImage,  author->{name, "slug": slug.current}, primaryTopic->{title, "slug": slug.current}}
export type FEATURED_ARTICLES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  featuredImage: EditorialImage;
  author: {
    name: string;
    slug: string;
  };
  primaryTopic: {
    title: string;
    slug: string;
  };
}>;

// Source: sanity/queries/content.ts
// Variable: TOPIC_BY_SLUG_QUERY
// Query: *[_type == "topic" && slug.current == $slug][0]{  ..., "slug": slug.current, relatedTopics[]->{title, "slug": slug.current},  featuredContent[]->{_type, _id, title, "slug": slug.current, summary, excerpt, featuredImage}}
export type TOPIC_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "topic";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: string;
  shortDescription: string;
  introduction?: RichText;
  heroImage: EditorialImage;
  featuredContent: Array<
    | {
        _type: "article";
        _id: string;
        title: string;
        slug: string;
        summary: null;
        excerpt: string;
        featuredImage: EditorialImage;
      }
    | {
        _type: "book";
        _id: string;
        title: string;
        slug: string;
        summary: null;
        excerpt: null;
        featuredImage: null;
      }
    | {
        _type: "podcastEpisode";
        _id: string;
        title: string;
        slug: string;
        summary: string;
        excerpt: null;
        featuredImage: EditorialImage;
      }
    | {
        _type: "video";
        _id: string;
        title: string;
        slug: string;
        summary: string;
        excerpt: null;
        featuredImage: EditorialImage;
      }
  > | null;
  relatedTopics: Array<{
    title: string;
    slug: string;
  }> | null;
  seo?: Seo;
} | null;

// Source: sanity/queries/content.ts
// Variable: TOPICS_QUERY
// Query: *[_type == "topic"] | order(title asc){  _id, title, "slug": slug.current, shortDescription, heroImage}
export type TOPICS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  shortDescription: string;
  heroImage: EditorialImage;
}>;

// Source: sanity/queries/content.ts
// Variable: PODCAST_EPISODE_BY_SLUG_QUERY
// Query: *[_type == "podcastEpisode" && slug.current == $slug][0]{  ..., "slug": slug.current, author->{name, "slug": slug.current}, guests[]->{name, "slug": slug.current, professionalTitle, portrait},  primaryTopic->{title, "slug": slug.current}, secondaryTopics[]->{title, "slug": slug.current}}
export type PODCAST_EPISODE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "podcastEpisode";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: string;
  summary: string;
  publishedAt: string;
  author: {
    name: string;
    slug: string;
  } | null;
  primaryTopic: {
    title: string;
    slug: string;
  };
  secondaryTopics: Array<{
    title: string;
    slug: string;
  }> | null;
  featuredImage: EditorialImage;
  featured?: boolean;
  seo?: Seo;
  migration?: MigrationMetadata;
  episodeNumber?: number;
  duration?: string;
  guests: Array<{
    name: string;
    slug: string;
    professionalTitle: string | null;
    portrait: EditorialImage;
  }> | null;
  guestNotes?: string;
  audioUrl?: string;
  platformLinks?: Array<
    {
      _key: string;
    } & ExternalLink
  >;
  videoUrl?: string;
  keyIdeas?: Array<string>;
  transcript?: RichText;
  showNotes?: RichText;
  relatedContent?: ArrayOf<
    | ArticleReference
    | BookReference
    | PageReference
    | PodcastEpisodeReference
    | VideoReference
  >;
} | null;

// Source: sanity/queries/content.ts
// Variable: PODCAST_EPISODES_QUERY
// Query: *[_type == "podcastEpisode"] | order(publishedAt desc)[$offset...$limit]{  _id, title, "slug": slug.current, summary, publishedAt, episodeNumber, duration, featuredImage,  guests[]->{name, "slug": slug.current}, primaryTopic->{title, "slug": slug.current}}
export type PODCAST_EPISODES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string;
  publishedAt: string;
  episodeNumber: number | null;
  duration: string | null;
  featuredImage: EditorialImage;
  guests: Array<{
    name: string;
    slug: string;
  }> | null;
  primaryTopic: {
    title: string;
    slug: string;
  };
}>;

// Source: sanity/queries/content.ts
// Variable: VIDEO_BY_SLUG_QUERY
// Query: *[_type == "video" && slug.current == $slug][0]{  ..., "slug": slug.current, author->{name, "slug": slug.current},  primaryTopic->{title, "slug": slug.current}, secondaryTopics[]->{title, "slug": slug.current}}
export type VIDEO_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: string;
  summary: string;
  publishedAt: string;
  author: {
    name: string;
    slug: string;
  } | null;
  primaryTopic: {
    title: string;
    slug: string;
  };
  secondaryTopics: Array<{
    title: string;
    slug: string;
  }> | null;
  featuredImage: EditorialImage;
  featured?: boolean;
  seo?: Seo;
  migration?: MigrationMetadata;
  provider: "other" | "vimeo" | "youtube";
  videoUrl: string;
  providerVideoId?: string;
  duration?: string;
  keyTakeaways?: Array<string>;
  transcript?: RichText;
  notes?: RichText;
  relatedContent?: ArrayOf<
    | ArticleReference
    | BookReference
    | PageReference
    | PodcastEpisodeReference
    | VideoReference
  >;
} | null;

// Source: sanity/queries/content.ts
// Variable: VIDEOS_QUERY
// Query: *[_type == "video"] | order(publishedAt desc)[$offset...$limit]{  _id, title, "slug": slug.current, summary, publishedAt, provider, duration, featuredImage,  primaryTopic->{title, "slug": slug.current}}
export type VIDEOS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string;
  publishedAt: string;
  provider: "other" | "vimeo" | "youtube";
  duration: string | null;
  featuredImage: EditorialImage;
  primaryTopic: {
    title: string;
    slug: string;
  };
}>;

// Source: sanity/queries/content.ts
// Variable: APPROVED_TESTIMONIALS_QUERY
// Query: *[_type == "testimonial" && approvalStatus == "approved"] | order(approvedAt desc){  _id, quote, attributionName, attributionTitle, attributionOrganization, portrait, videoUrl,  program->{title, "slug": slug.current, pageKind}}
export type APPROVED_TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string;
  quote: string;
  attributionName: string;
  attributionTitle: string | null;
  attributionOrganization: string | null;
  portrait: EditorialImage;
  videoUrl: string | null;
  program: {
    title: string;
    slug: string;
    pageKind: "contact" | "legal" | "offer" | "roadmap" | "standard";
  } | null;
}>;

// Source: sanity/queries/content.ts
// Variable: FEATURED_TESTIMONIALS_QUERY
// Query: *[_type == "testimonial" && approvalStatus == "approved" && featured == true] | order(approvedAt desc)[0...$limit]{  _id, quote, attributionName, attributionTitle, attributionOrganization, portrait, videoUrl,  program->{title, "slug": slug.current, pageKind}}
export type FEATURED_TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string;
  quote: string;
  attributionName: string;
  attributionTitle: string | null;
  attributionOrganization: string | null;
  portrait: EditorialImage;
  videoUrl: string | null;
  program: {
    title: string;
    slug: string;
    pageKind: "contact" | "legal" | "offer" | "roadmap" | "standard";
  } | null;
}>;

// Source: sanity/queries/content.ts
// Variable: BOOK_BY_SLUG_QUERY
// Query: *[_type == "book" && slug.current == $slug][0]{  ..., "slug": slug.current, authors[]->{name, "slug": slug.current, professionalTitle}, primaryTopic->{title, "slug": slug.current}}
export type BOOK_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "book";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  subtitle?: string;
  slug: string;
  description?: RichText;
  cover: EditorialImage;
  authors: Array<{
    name: string;
    slug: string;
    professionalTitle: string | null;
  }>;
  publicationDate?: string;
  isbn?: string;
  purchaseLinks?: Array<
    {
      _key: string;
    } & ExternalLink
  >;
  primaryTopic: {
    title: string;
    slug: string;
  } | null;
  relatedTopics?: Array<
    {
      _key: string;
    } & TopicReference
  >;
  relatedContent?: ArrayOf<
    ArticleReference | PageReference | PodcastEpisodeReference | VideoReference
  >;
  featured?: boolean;
  seo?: Seo;
} | null;

// Source: sanity/queries/content.ts
// Variable: FAQS_BY_CONTEXT_QUERY
// Query: *[_type == "faq" && $context in contexts] | order(order asc){  _id, question, answer, contexts, relatedPages[]->{title, "slug": slug.current}}
export type FAQS_BY_CONTEXT_QUERY_RESULT = Array<{
  _id: string;
  question: string;
  answer: RichText;
  contexts: Array<string>;
  relatedPages: Array<{
    title: string;
    slug: string;
  }> | null;
}>;

// Source: sanity/queries/content.ts
// Variable: ACTIVE_REDIRECTS_QUERY
// Query: *[_type == "redirect" && active == true]{source, destination, statusCode}
export type ACTIVE_REDIRECTS_QUERY_RESULT = Array<{
  source: string;
  destination: string;
  statusCode: 301 | 302 | 307 | 308;
}>;

// Source: sanity/queries/content.ts
// Variable: PAGE_BY_SLUG_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{  ..., "slug": slug.current, relatedContent[]->{_type, _id, title, "slug": slug.current, summary, excerpt, featuredImage}}
export type PAGE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: string;
  pageKind: "contact" | "legal" | "offer" | "roadmap" | "standard";
  summary?: string;
  body?: RichText;
  heroImage: EditorialImage;
  primaryCta?: CtaLink;
  relatedContent: Array<
    | {
        _type: "article";
        _id: string;
        title: string;
        slug: string;
        summary: null;
        excerpt: string;
        featuredImage: EditorialImage;
      }
    | {
        _type: "book";
        _id: string;
        title: string;
        slug: string;
        summary: null;
        excerpt: null;
        featuredImage: null;
      }
    | {
        _type: "podcastEpisode";
        _id: string;
        title: string;
        slug: string;
        summary: string;
        excerpt: null;
        featuredImage: EditorialImage;
      }
    | {
        _type: "topic";
        _id: string;
        title: string;
        slug: string;
        summary: null;
        excerpt: null;
        featuredImage: null;
      }
    | {
        _type: "video";
        _id: string;
        title: string;
        slug: string;
        summary: string;
        excerpt: null;
        featuredImage: EditorialImage;
      }
  > | null;
  seo?: Seo;
  migration?: MigrationMetadata;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "siteSettings" && _id == "siteSettings"][0]{\n  ..., founder->{name, "slug": slug.current, professionalTitle, portrait, sameAs}\n}': SITE_SETTINGS_QUERY_RESULT;
    '*[_type == "person" && slug.current == $slug][0]{\n  ..., "slug": slug.current\n}': PERSON_BY_SLUG_QUERY_RESULT;
    '*[_type == "person" && slug.current == "jack-skeen"][0]{\n  ..., "slug": slug.current\n}': JACK_PROFILE_QUERY_RESULT;
    '*[_type == "article" && slug.current == $slug][0]{\n  ..., "slug": slug.current, author->{name, "slug": slug.current, professionalTitle, portrait},\n  primaryTopic->{title, "slug": slug.current}, secondaryTopics[]->{title, "slug": slug.current},\n  relatedContent[]->{_type, _id, title, "slug": slug.current, summary, excerpt, featuredImage}\n}': ARTICLE_BY_SLUG_QUERY_RESULT;
    '*[_type == "article"] | order(publishedAt desc)[$offset...$limit]{\n  _id, title, "slug": slug.current, excerpt, publishedAt, updatedAt, featuredImage,\n  author->{name, "slug": slug.current}, primaryTopic->{title, "slug": slug.current}\n}': ARTICLES_QUERY_RESULT;
    '*[_type == "article" && (primaryTopic->slug.current == $slug || $slug in secondaryTopics[]->slug.current)] | order(publishedAt desc){\n  _id, title, "slug": slug.current, excerpt, publishedAt, featuredImage,\n  author->{name, "slug": slug.current}, primaryTopic->{title, "slug": slug.current}\n}': ARTICLES_BY_TOPIC_QUERY_RESULT;
    '*[_type == "article" && featured == true] | order(publishedAt desc)[0...$limit]{\n  _id, title, "slug": slug.current, excerpt, publishedAt, featuredImage,\n  author->{name, "slug": slug.current}, primaryTopic->{title, "slug": slug.current}\n}': FEATURED_ARTICLES_QUERY_RESULT;
    '*[_type == "topic" && slug.current == $slug][0]{\n  ..., "slug": slug.current, relatedTopics[]->{title, "slug": slug.current},\n  featuredContent[]->{_type, _id, title, "slug": slug.current, summary, excerpt, featuredImage}\n}': TOPIC_BY_SLUG_QUERY_RESULT;
    '*[_type == "topic"] | order(title asc){\n  _id, title, "slug": slug.current, shortDescription, heroImage\n}': TOPICS_QUERY_RESULT;
    '*[_type == "podcastEpisode" && slug.current == $slug][0]{\n  ..., "slug": slug.current, author->{name, "slug": slug.current}, guests[]->{name, "slug": slug.current, professionalTitle, portrait},\n  primaryTopic->{title, "slug": slug.current}, secondaryTopics[]->{title, "slug": slug.current}\n}': PODCAST_EPISODE_BY_SLUG_QUERY_RESULT;
    '*[_type == "podcastEpisode"] | order(publishedAt desc)[$offset...$limit]{\n  _id, title, "slug": slug.current, summary, publishedAt, episodeNumber, duration, featuredImage,\n  guests[]->{name, "slug": slug.current}, primaryTopic->{title, "slug": slug.current}\n}': PODCAST_EPISODES_QUERY_RESULT;
    '*[_type == "video" && slug.current == $slug][0]{\n  ..., "slug": slug.current, author->{name, "slug": slug.current},\n  primaryTopic->{title, "slug": slug.current}, secondaryTopics[]->{title, "slug": slug.current}\n}': VIDEO_BY_SLUG_QUERY_RESULT;
    '*[_type == "video"] | order(publishedAt desc)[$offset...$limit]{\n  _id, title, "slug": slug.current, summary, publishedAt, provider, duration, featuredImage,\n  primaryTopic->{title, "slug": slug.current}\n}': VIDEOS_QUERY_RESULT;
    '*[_type == "testimonial" && approvalStatus == "approved"] | order(approvedAt desc){\n  _id, quote, attributionName, attributionTitle, attributionOrganization, portrait, videoUrl,\n  program->{title, "slug": slug.current, pageKind}\n}': APPROVED_TESTIMONIALS_QUERY_RESULT;
    '*[_type == "testimonial" && approvalStatus == "approved" && featured == true] | order(approvedAt desc)[0...$limit]{\n  _id, quote, attributionName, attributionTitle, attributionOrganization, portrait, videoUrl,\n  program->{title, "slug": slug.current, pageKind}\n}': FEATURED_TESTIMONIALS_QUERY_RESULT;
    '*[_type == "book" && slug.current == $slug][0]{\n  ..., "slug": slug.current, authors[]->{name, "slug": slug.current, professionalTitle}, primaryTopic->{title, "slug": slug.current}\n}': BOOK_BY_SLUG_QUERY_RESULT;
    '*[_type == "faq" && $context in contexts] | order(order asc){\n  _id, question, answer, contexts, relatedPages[]->{title, "slug": slug.current}\n}': FAQS_BY_CONTEXT_QUERY_RESULT;
    '*[_type == "redirect" && active == true]{source, destination, statusCode}': ACTIVE_REDIRECTS_QUERY_RESULT;
    '*[_type == "page" && slug.current == $slug][0]{\n  ..., "slug": slug.current, relatedContent[]->{_type, _id, title, "slug": slug.current, summary, excerpt, featuredImage}\n}': PAGE_BY_SLUG_QUERY_RESULT;
  }
}
